//! Embedded Svelte viewer bundle.
//!
//! The gzipped IIFE bundle is committed at `vendor/relux-viewer.js.gz`
//! and baked into the binary at compile time. The per-test `event.html`
//! emitter at `report::event_html` decompresses these bytes and inlines
//! them into a `<script>` tag alongside the test's `window.RELUX_DATA`
//! payload.
//!
//! The vendored artifact is regenerated by `just viewer-build`; a
//! pre-commit hook and CI step verify it stays in sync with the
//! `viewer/` sources.

/// Gzipped IIFE bundle bytes; identical to the file on disk at
/// `vendor/relux-viewer.js.gz` at compile time.
pub fn bundle_gz() -> &'static [u8] {
    include_bytes!("../../../vendor/relux-viewer.js.gz")
}

#[cfg(test)]
mod tests {
    use super::*;
    use flate2::read::GzDecoder;
    use std::io::Read;

    #[test]
    fn embedded_bundle_is_valid_gzip_with_expected_entry() {
        let bytes = bundle_gz();
        assert!(!bytes.is_empty(), "embedded bundle is empty");

        let mut decoder = GzDecoder::new(bytes);
        let mut js = String::new();
        decoder
            .read_to_string(&mut js)
            .expect("bundle is not valid gzip");

        // The bundle reads `window.RELUX_DATA` at mount time
        // (see viewer/src/main.ts). esbuild preserves this string as
        // a property access; if it disappears, the entry-point logic
        // has been replaced or the wrong artifact was embedded.
        assert!(
            js.contains("RELUX_DATA"),
            "decompressed bundle missing 'RELUX_DATA' entry hook"
        );
    }
}
