core:
  - changed-files:
      - any-glob-to-any-file: crates/relux-core/**

ast:
  - changed-files:
      - any-glob-to-any-file: crates/relux-ast/**

lexer:
  - changed-files:
      - any-glob-to-any-file: crates/relux-lexer/**

parser:
  - changed-files:
      - any-glob-to-any-file: crates/relux-parser/**

ir:
  - changed-files:
      - any-glob-to-any-file: crates/relux-ir/**

resolver:
  - changed-files:
      - any-glob-to-any-file: crates/relux-resolver/**

runtime:
  - changed-files:
      - any-glob-to-any-file: crates/relux-runtime/**

viewer:
  - changed-files:
      - any-glob-to-any-file:
          - viewer/**
          - vendor/relux-viewer.js.gz

cli:
  - changed-files:
      - any-glob-to-any-file: crates/relux-cli/**

docs:
  - changed-files:
      - any-glob-to-any-file: docs/**

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**

e2e:
  - changed-files:
      - any-glob-to-any-file: tests/**

editors:
  - changed-files:
      - any-glob-to-any-file: editors/**

rfc:
  - changed-files:
      - any-glob-to-any-file: rfc/**
