#!/usr/bin/env bash
# Fail if any tracked text file contains non-ASCII bytes.
# Binary files (detected by grep) are skipped automatically.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Paths excluded from the ASCII check.
#   CHANGELOG.md   - generated by release-please, we do not author it.
#   CLAUDE.md      - agent instructions (prose, not code).
#   docs/**/*.md   - mdbook sources (prose, not code).
#   rfc/*.md       - design docs (prose, not code).
excludes=(
    ':(exclude)CHANGELOG.md'
    ':(exclude)CLAUDE.md'
    ':(exclude,glob)docs/**/*.md'
    ':(exclude,glob)rfc/*.md'
)

bad=$(git ls-files -z -- . "${excludes[@]}" \
    | LC_ALL=C xargs -0 grep -nP '[^\x00-\x7F]' \
        --binary-files=without-match \
        --color=never \
        2>/dev/null || true)

if [[ -n "$bad" ]]; then
    echo "ERROR: non-ASCII bytes found in tracked source:"
    echo "$bad"
    echo
    echo "Use ASCII equivalents, or \\u{} escapes in Rust source."
    exit 1
fi
